### ISSUE TITLE
Using Dask's map functionality slower than using single process native map function

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/nocap#17]
When using Dask's[ client.map](https://docs.dask.org/en/stable/bag.html) slower than using native `map` is much slower. 

Additionally another error arrives:

```
- [ ] distributed.core - ERROR - Exception while handling op register-client
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/core.py", line 820, in _handle_comm
    result = await result
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/scheduler.py", line 5250, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/core.py", line 873, in handle_stream
    msgs = await comm.read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/comm/tcp.py", line 235, in read
    n = await stream.read_into(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 474, in read_into
    self._try_inline_read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 844, in _try_inline_read
    pos = self._read_to_buffer_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 757, in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
OSError: [Errno 22] Invalid argument
Task exception was never retrieved
future: <Task finished name='Task-31363' coro=<Server._handle_comm() done, defined at /Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/core.py:726> exception=OSError(22, 'Invalid argument')>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/core.py", line 820, in _handle_comm
    result = await result
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/scheduler.py", line 5250, in add_client
    await self.handle_stream(comm=comm, extra={"client": client})
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/core.py", line 873, in handle_stream
    msgs = await comm.read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/comm/tcp.py", line 235, in read
    n = await stream.read_into(chunk)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 474, in read_into
    self._try_inline_read()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 844, in _try_inline_read
    pos = self._read_to_buffer_loop()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 757, in _read_to_buffer_loop
    if self._read_to_buffer() == 0:
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 869, in _read_to_buffer
    bytes_read = self.read_from_fd(buf)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/iostream.py", line 1138, in read_from_fd
    return self.socket.recv_into(buf, len(buf))
OSError: [Errno 22] Invalid argument
```

**Comment by sabzo** [comment]
No longer working on this
