### ISSUE TITLE
Dockets file not working for sqlite 

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/nocap#23]
For some reason, the Dockets file when read into sqllite has no keys:

<img width="913" alt="image" src="https://github.com/harvard-lil/nocap/assets/2899124/30610092-6a34-4fbe-8f35-0f88e4e8dba0">

This is causing "key doesn't exist" errors

## to reproduce:
initialize nocap with .bz2 files
```python3
# get file paths
opinions_fn = f'{path}opinions-2022-12-31.csv.bz2'
courts_fn = f'{path}courts-2022-12-31.csv.bz2'
dockets_fn = f'{path}dockets-2022-12-31.csv.bz2'
opinion_clusters_fn = f'{path}opinion-clusters-2022-12-31.csv.bz2'
citation_fn = f'{path}citation-map-2022-12-31.csv.bz2'

# initalize nc
nc = lnc.NoCap(opinions_fn, opinion_clusters_fn, courts_fn, dockets_fn, citation_fn)

# check length of docket keys
len(list(nc._df_dockets.keys()))
```

**Comment by sabzo** [comment]
error looks like:
```python3
KeyError: 62526835
DEBUG:root:process_df: client.map
ERROR:root:62428550
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lil_nocap/__init__.py", line 459, in start
    result = future.result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 451, in result
    return self.__get_result()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
    raise self._exception
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lil_nocap/__init__.py", line 337, in process_df
    docket_rows = list(map(lambda x: dockets[int(x["docket_id"])], cluster_rows))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/lil_nocap/__init__.py", line 337, in <lambda>
    docket_rows = list(map(lambda x: dockets[int(x["docket_id"])], cluster_rows))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/sqlitedict.py", line 305, in __getitem__
    raise KeyError(key)
KeyError: 62428550
```
