### ISSUE TITLE
Running locally is impractical

### ISSUE THREAD

**Issue by sabzo** [harvard-lil/nocap#6]
## Several issues when running locally:

* Memory to import the datasets (need at least 32GB) besides the opinions dataset
* When importing the `opinions` dataset chunk by chunk (500 rows at a time) there's a memory allocation error that shows up after several hours:
```
OSError: [Errno 12] Cannot allocate memory
2023-03-21 08:48:17,358 - tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 6 memory: 22 MB fds: 26>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/system_monitor.py", line 134, in update
    net_ioc = psutil.net_io_counters()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
 SystemMonitor.update of <SystemMonitor: cpu: 6 memory: 22 MB fds: 26>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/system_monitor.py", line 134, in update
    net_ioc = psutil.net_io_counters()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
m_monitor.py", line 134, in update
    net_ioc = psutil.net_io_counters()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
2023-03-21 08:49:12,051 - tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 1 memory: 24 MB fds: 26>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/system_monitor.py", line 134, in update
    net_ioc = psutil.net_io_counters()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
2023-03-21 08:51:10,108 - tornado.application - ERROR - Exception in callback <bound method SystemMonitor.update of <SystemMonitor: cpu: 6 memory: 25 MB fds: 26>>
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/tornado/ioloop.py", line 921, in _run
    val = self.callback()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/system_monitor.py", line 134, in update
    net_ioc = psutil.net_io_counters()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/psutil/__init__.py", line 2114, in net_io_counters
    rawdict = _psplatform.net_io_counters()
OSError: [Errno 12] Cannot allocate memory
```

## Solution:
Create a distributed cloud cluster with hundreds of cores at least that can be turned on and off automatically or through a click

For example something like this:
* https://towardsdatascience.com/bootstrapping-dask-on-1000-cores-with-aws-fargate-1e1b7fd1a32c
* https://aws.amazon.com/blogs/machine-learning/machine-learning-on-distributed-dask-using-amazon-sagemaker-and-aws-fargate/

**Comment by sabzo** [comment]
## when trying Dask futures
```
Traceback (most recent call last):
  File "/Users/sabelosethumhlambi/Documents/GitHub/nocap/lil_nocap/nocap.py", line 288, in <module>
    NoCap.cli()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/Users/sabelosethumhlambi/Documents/GitHub/nocap/lil_nocap/nocap.py", line 37, in cli
    NoCap(o, oc, c, d, cm).start()
  File "/Users/sabelosethumhlambi/Documents/GitHub/nocap/lil_nocap/nocap.py", line 279, in start
    future = self._client.submit(self.process_df, df)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/client.py", line 1897, in submit
    futures = self._graph_to_futures(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/client.py", line 3024, in _graph_to_futures
    dsk = dsk.__dask_distributed_pack__(self, keyset, annotations)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dask/highlevelgraph.py", line 1078, in __dask_distributed_pack__
    "state": layer.__dask_distributed_pack__(
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/dask/highlevelgraph.py", line 432, in __dask_distributed_pack__
    dsk = toolz.valmap(dumps_task, dsk)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/toolz/dicttoolz.py", line 85, in valmap
    rv.update(zip(d.keys(), map(func, d.values())))
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/worker.py", line 3024, in dumps_task
    return {"function": dumps_function(task[0]), "args": warn_dumps(task[1:])}
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/worker.py", line 2988, in dumps_function
    result = pickle.dumps(func)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/distributed/protocol/pickle.py", line 81, in dumps
    result = cloudpickle.dumps(x, **dump_kwargs)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 73, in dumps
    cp.dump(obj)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/cloudpickle/cloudpickle_fast.py", line 632, in dump
    return Pickler.dump(self, obj)
TypeError: cannot pickle '_asyncio.Task' object
```

**Comment by sabzo** [comment]
Pickle error is also noted here: 
* https://github.com/dask/dask/issues/5317
  -- but using the solution to install/upgrade `cloudpickle` didn't he
* https://github.com/dask/distributed/issues/4645

**Comment by sabzo** [comment]
solved by using sqlite, pandas in chunks, dicts when appropriate, and reading compressed files
